/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.data.jpa)
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.io.springfox.springfox.swagger2)
    api(libs.io.springfox.springfox.swagger.ui)
    api(libs.org.springframework.boot.spring.boot.starter.security)
    api(libs.io.jsonwebtoken.jjwt.api)
    api(libs.io.jsonwebtoken.jjwt.impl)
    api(libs.io.jsonwebtoken.jjwt.jackson)
    api(libs.org.springframework.boot.spring.boot.starter.validation)
    api(libs.mysql.mysql.connector.java)
    runtimeOnly(libs.com.h2database.h2)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.org.springframework.security.spring.security.test)
    compileOnly("org.projectlombok:lombok:1.18.32")
    annotationProcessor("org.projectlombok:lombok:1.18.32")
}

group = "com.prueba"
version = "0.0.1-SNAPSHOT"
description = "Prueba"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
